Repository att-cloudnative-labs/kubesweeper, pull requests merged in 2019-04, with the labels that each got.

#3 Add shields to README
  README.md
Labels: enhancement, good first issue

#4 add Dockerfile
  Dockerfile
  README.md
Labels: enhancement

#10 Add Kubernetes resource yaml files for installation as a CronJob
  install/cronjob.yaml
  install/namespace.yaml
  install/rbac.yaml
  install/serviceaccount.yaml
Labels: enhancement

#6 Feature/configurable function map
  Dockerfile
  config.go
  configs/config.yaml
  go.mod
  go.sum
  main.go
Labels: enhancement

#1 Add initial main.go code with main implementation
  .gitignore
  Dockerfile
  README.md
  config.go
  configs/config.yaml
  go.mod
  go.sum
  main.go
Labels: enhancement, good first issue, help wanted

#15 Add ServiceAccountName, remove outer for loop, update default restart count
  configs/config.yaml
  install/cronjob.yaml
  main.go
Labels: enhancement
